# PHP
phpfpm:
  extends:
    file: php-fpm-5.3.yml
    service: phpfpm
  links:
    - db:db
  volumes:
    - ./:/var/www/html

# NGINX
nginx:
  image: nginx
  ports:
    - "8000:80"
  links:
    - phpfpm:phpfpm
  volumes:
    - ./docker/nginx/conf.d:/etc/nginx/conf.d
    - ./:/var/www/html
    - ./docker/log/nginx:/var/log/nginx

# MYSQL
db:
  image: mysql
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
  volumes:
    - /docker/mysql/databases:/var/lib/mysql
    - /docker/mysql/dump:/docker-entrypoint-initdb.d
    - /docker/log/mysql:/var/log/mysql
